buildscript {
    repositories { mavenCentral() }
}

allprojects {
    ext {
        gdxVersion = '1.13.1'
        gdxTeaVMVersion = '1.2.0'
    }
    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    }
}

subprojects {
    apply plugin: 'java'
    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    compileJava {
        options.encoding = 'UTF-8'
    }
}
